
package edu.boun.swe574.fsn.common.client.search;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SearchService", targetNamespace = "http://ws.backend.fsn.swe574.boun.edu/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SearchService {


    /**
     * 
     * @param token
     * @param listOfPreferredIngredients
     * @return
     *     returns edu.boun.swe574.fsn.common.client.search.GetRecipeFeedsResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public GetRecipeFeedsResponse searchForRecipes(
        @WebParam(name = "token", partName = "token")
        String token,
        @WebParam(name = "listOfPreferredIngredients", partName = "listOfPreferredIngredients")
        LongArray listOfPreferredIngredients);

}
