
package edu.boun.swe574.fsn.common.client.food;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FoodsService", targetNamespace = "http://ws.backend.fsn.swe574.boun.edu/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FoodsService {


    /**
     * 
     * @param recipe
     * @param token
     * @return
     *     returns edu.boun.swe574.fsn.common.client.food.BaseServiceResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public BaseServiceResponse createRecipe(
        @WebParam(name = "token", partName = "token")
        String token,
        @WebParam(name = "recipe", partName = "recipe")
        RecipeInfo recipe);

    /**
     * 
     * @param queryString
     * @param token
     * @return
     *     returns edu.boun.swe574.fsn.common.client.food.GetIngredientsResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public GetIngredientsResponse getIngredients(
        @WebParam(name = "token", partName = "token")
        String token,
        @WebParam(name = "queryString", partName = "queryString")
        String queryString);

    /**
     * 
     * @param recipe
     * @param token
     * @param parentRecipeId
     * @param revisionNote
     * @return
     *     returns edu.boun.swe574.fsn.common.client.food.BaseServiceResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public BaseServiceResponse createNewVersionOfRecipe(
        @WebParam(name = "token", partName = "token")
        String token,
        @WebParam(name = "recipe", partName = "recipe")
        RecipeInfo recipe,
        @WebParam(name = "parentRecipeId", partName = "parentRecipeId")
        long parentRecipeId,
        @WebParam(name = "revisionNote", partName = "revisionNote")
        String revisionNote);

    /**
     * 
     * @param recipeId
     * @param token
     * @return
     *     returns edu.boun.swe574.fsn.common.client.food.GetRecipeResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public GetRecipeResponse getRecipe(
        @WebParam(name = "token", partName = "token")
        String token,
        @WebParam(name = "recipeId", partName = "recipeId")
        long recipeId);

    /**
     * 
     * @param recipeId
     * @param token
     * @param rateValue
     * @return
     *     returns edu.boun.swe574.fsn.common.client.food.BaseServiceResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public BaseServiceResponse rateRecipe(
        @WebParam(name = "token", partName = "token")
        String token,
        @WebParam(name = "recipeId", partName = "recipeId")
        long recipeId,
        @WebParam(name = "rateValue", partName = "rateValue")
        int rateValue);

    /**
     * 
     * @param recipeId
     * @param token
     * @return
     *     returns edu.boun.swe574.fsn.common.client.food.GetRevisionHistoryOfRecipeResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public GetRevisionHistoryOfRecipeResponse getRevisionHistoryOfRecipe(
        @WebParam(name = "token", partName = "token")
        String token,
        @WebParam(name = "recipeId", partName = "recipeId")
        long recipeId);

}
