
package edu.boun.swe574.fsn.common.client.auth;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AuthService", targetNamespace = "http://ws.backend.fsn.swe574.boun.edu/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthService {


    /**
     * 
     * @param email
     * @param name
     * @param surname
     * @param password
     * @return
     *     returns edu.boun.swe574.fsn.common.client.auth.BaseServiceResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public BaseServiceResponse register(
        @WebParam(name = "email", partName = "email")
        String email,
        @WebParam(name = "name", partName = "name")
        String name,
        @WebParam(name = "surname", partName = "surname")
        String surname,
        @WebParam(name = "password", partName = "password")
        String password);

    /**
     * 
     * @param email
     * @param password
     * @return
     *     returns edu.boun.swe574.fsn.common.client.auth.LoginResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public LoginResponse login(
        @WebParam(name = "email", partName = "email")
        String email,
        @WebParam(name = "password", partName = "password")
        String password);

}
