
package edu.boun.swe574.fsn.common.client.auth;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AuthService", targetNamespace = "http://ws.backend.fsn.swe574.boun.edu/", wsdlLocation = "http://localhost:8080/FSN_SERVER/fsnws_auth?wsdl")
public class AuthService_Service
    extends Service
{  

    private final static URL AUTHSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/FSN_SERVER/fsnws_auth?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        AUTHSERVICE_WSDL_LOCATION = url;
    }

    public AuthService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthService_Service() {
        super(AUTHSERVICE_WSDL_LOCATION, new QName("http://ws.backend.fsn.swe574.boun.edu/", "AuthService"));
    }

    /**
     * 
     * @return
     *     returns AuthService
     */
    @WebEndpoint(name = "AuthServicePort")
    public AuthService getAuthServicePort() {
        return (AuthService)super.getPort(new QName("http://ws.backend.fsn.swe574.boun.edu/", "AuthServicePort"), AuthService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthService
     */
    @WebEndpoint(name = "AuthServicePort")
    public AuthService getAuthServicePort(WebServiceFeature... features) {
        return (AuthService)super.getPort(new QName("http://ws.backend.fsn.swe574.boun.edu/", "AuthServicePort"), AuthService.class, features);
    }

}
